/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyHeadline {
    }
    interface ProgressBar {
        "currentnumber": string;
        "goal": string;
    }
}
declare global {
    interface HTMLMyHeadlineElement extends Components.MyHeadline, HTMLStencilElement {
    }
    var HTMLMyHeadlineElement: {
        prototype: HTMLMyHeadlineElement;
        new (): HTMLMyHeadlineElement;
    };
    interface HTMLProgressBarElement extends Components.ProgressBar, HTMLStencilElement {
    }
    var HTMLProgressBarElement: {
        prototype: HTMLProgressBarElement;
        new (): HTMLProgressBarElement;
    };
    interface HTMLElementTagNameMap {
        "my-headline": HTMLMyHeadlineElement;
        "progress-bar": HTMLProgressBarElement;
    }
}
declare namespace LocalJSX {
    interface MyHeadline {
    }
    interface ProgressBar {
        "currentnumber"?: string;
        "goal"?: string;
        "onValueChanged"?: (event: CustomEvent<string>) => void;
    }
    interface IntrinsicElements {
        "my-headline": MyHeadline;
        "progress-bar": ProgressBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-headline": LocalJSX.MyHeadline & JSXBase.HTMLAttributes<HTMLMyHeadlineElement>;
            "progress-bar": LocalJSX.ProgressBar & JSXBase.HTMLAttributes<HTMLProgressBarElement>;
        }
    }
}
